name: CI Sanity
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  sanity:
    name: CI / sanity
    runs-on: ubuntu-24.04
    concurrency:
      group: sanity-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v5
      - name: Green light
        run: |
          printf 'green light\n'
          printf '## CI Sanity\n\nAll good here.\n' >> "$GITHUB_STEP_SUMMARY"
